### ISSUE TITLE
Use a library for signals and slots

### ISSUE THREAD

**Issue by adazem009** [scratchcpp/libscratchcpp#475]
There are many cases where a feature similar to Qt signals and slots is needed, especially in the Engine class.

For example, to run a function when a redraw is requested from the engine, you need to set a callback using `Engine::setRedrawHandler()`. The callback will then be called internally by the engine.
Another example could be `Engine::setAddMonitorHandler()` which is used to set a callback for when a stage monitor is added.
This approach makes the API difficult to use and maintain.

**Comment by Arcnor** [comment]
I'm not sure I'll have time for a while, but have you seen the https://github.com/palacaze/sigslot library? From my tests it was well constructed, better than reinventing the wheel IMHO.

**Comment by adazem009** [comment]
> I'm not sure I'll have time for a while, but have you seen the https://github.com/palacaze/sigslot library? From my tests it was well constructed, better than reinventing the wheel IMHO.

I didn't mean you should work on this or anything like that, I only needed some better ideas to solve this problem... that's why I pinged you.
Anyway, that library looks good and it's single-header which perfectly suits my needs. Thanks.
